version: '3.9'
services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - ${APP_PORT}:8000
    networks:
      - default

networks:
  default:
    name: docker_python_fastapi_network
    driver: bridge

volumes:
  data:
    name: docker_python_fastapi_data
    driver: local
