version: '3.9'
services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 9000:9000
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
